services:
  app:
    container_name: rm-console-app
    image: rm-console:latest
    build:
      context: .
      dockerfile: Containerfile
      args:
        - VITE_API_BASE_URL=https://api.trotot.vn/api
    ports:
      - "8181:8080"
    networks:
      rm-be-network:
        ipv4_address: 172.16.0.4
    restart: unless-stopped

networks:
  rm-be-network:
    external: true
